[project]
name = "cv-assignment-1"
version = "0.1.0"
description = "MSc Computer Vision Assignment 1"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "opencv-python",
    "matplotlib",
    "scipy",
    "scikit-image",
    "jupyter",
    "pillow",
    "pandas",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "pytest-cov",
    "black",
    "pylint",
]